//
// Created by dingjing on 23-11-27.
//

#ifndef GRACEFUL_WM_XMACRO_ATOMS_NET_SUPPORTED_H
#define GRACEFUL_WM_XMACRO_ATOMS_NET_SUPPORTED_H

#define GWM_NET_SUPPORTED_ATOMS_XMACRO \
GWM_ATOM_MACRO(_NET_SUPPORTED) \
GWM_ATOM_MACRO(_NET_SUPPORTING_WM_CHECK) \
GWM_ATOM_MACRO(_NET_WM_NAME) \
GWM_ATOM_MACRO(_NET_WM_VISIBLE_NAME) \
GWM_ATOM_MACRO(_NET_WM_MOVERESIZE) \
GWM_ATOM_MACRO(_NET_WM_STATE_STICKY) \
GWM_ATOM_MACRO(_NET_WM_STATE_FULLSCREEN) \
GWM_ATOM_MACRO(_NET_WM_STATE_DEMANDS_ATTENTION) \
GWM_ATOM_MACRO(_NET_WM_STATE_MODAL) \
GWM_ATOM_MACRO(_NET_WM_STATE_HIDDEN) \
GWM_ATOM_MACRO(_NET_WM_STATE_FOCUSED) \
GWM_ATOM_MACRO(_NET_WM_STATE) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_NORMAL) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_DOCK) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_DIALOG) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_UTILITY) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_TOOLBAR) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_SPLASH) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_MENU) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_DROPDOWN_MENU) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_POPUP_MENU) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_TOOLTIP) \
GWM_ATOM_MACRO(_NET_WM_WINDOW_TYPE_NOTIFICATION) \
GWM_ATOM_MACRO(_NET_WM_DESKTOP) \
GWM_ATOM_MACRO(_NET_WM_STRUT_PARTIAL) \
GWM_ATOM_MACRO(_NET_CLIENT_LIST) \
GWM_ATOM_MACRO(_NET_CLIENT_LIST_STACKING) \
GWM_ATOM_MACRO(_NET_CURRENT_DESKTOP) \
GWM_ATOM_MACRO(_NET_NUMBER_OF_DESKTOPS) \
GWM_ATOM_MACRO(_NET_DESKTOP_NAMES) \
GWM_ATOM_MACRO(_NET_DESKTOP_VIEWPORT) \
GWM_ATOM_MACRO(_NET_ACTIVE_WINDOW) \
GWM_ATOM_MACRO(_NET_CLOSE_WINDOW) \
GWM_ATOM_MACRO(_NET_MOVERESIZE_WINDOW)

#endif //GRACEFUL_WM_XMACRO_ATOMS_NET_SUPPORTED_H
