//
// Created by dingjing on 23-11-27.
//

#ifndef GRACEFUL_WM_XMACRO_ATOMS_RESET_H
#define GRACEFUL_WM_XMACRO_ATOMS_RESET_H

#define GWM_REST_ATOMS_XMACRO \
GWM_ATOM_MACRO(_NET_WM_USER_TIME) \
GWM_ATOM_MACRO(_NET_STARTUP_ID) \
GWM_ATOM_MACRO(_NET_WORKAREA) \
GWM_ATOM_MACRO(_NET_WM_ICON) \
GWM_ATOM_MACRO(WM_PROTOCOLS) \
GWM_ATOM_MACRO(WM_DELETE_WINDOW) \
GWM_ATOM_MACRO(UTF8_STRING) \
GWM_ATOM_MACRO(WM_STATE) \
GWM_ATOM_MACRO(WM_CLIENT_LEADER) \
GWM_ATOM_MACRO(WM_TAKE_FOCUS) \
GWM_ATOM_MACRO(WM_WINDOW_ROLE) \
GWM_ATOM_MACRO(GWM_SOCKET_PATH) \
GWM_ATOM_MACRO(GWM_CONFIG_PATH) \
GWM_ATOM_MACRO(GWM_SYNC) \
GWM_ATOM_MACRO(GWM_SHMLOG_PATH) \
GWM_ATOM_MACRO(GWM_PID) \
GWM_ATOM_MACRO(GWM_LOG_STREAM_SOCKET_PATH) \
GWM_ATOM_MACRO(GWM_FLOATING_WINDOW) \
GWM_ATOM_MACRO(_NET_REQUEST_FRAME_EXTENTS) \
GWM_ATOM_MACRO(_NET_FRAME_EXTENTS) \
GWM_ATOM_MACRO(_MOTIF_WM_HINTS) \
GWM_ATOM_MACRO(WM_CHANGE_STATE) \
GWM_ATOM_MACRO(MANAGER)

#endif //GRACEFUL_WM_XMACRO_ATOMS_RESET_H
